### ISSUE TITLE
Thanks for making this!

### ISSUE THREAD

**Issue by Noonlord** [rwnx/piku-dashboard#19]
First, sorry for writing an issue about this. But I figured that it would be easiest way to get in touch with you and knowing that code you wrote is being used is a great feeling. 

I use this since 5 months and it is really great! I share my server with friends and this gives them easy access to logs and restarts etc. It has been really great so far and thanks for building this.

**Comment by rwnx** [comment]
Thank you! I'd love to hear your thoughts re: improvements if you are actively using it. Feel free to open more issues :)
